//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public long article_id { get; set; }
        public string article_name { get; set; }
        public string article_description { get; set; }
        public string article_content { get; set; }
        public Nullable<int> article_type { get; set; }
        public string article_slugurl { get; set; }
        public string article_photo_sm { get; set; }
        public string article_photo_lg { get; set; }
        public string tags { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> votes { get; set; }
        public Nullable<int> art_cat_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual User User { get; set; }
        public virtual category category { get; set; }
    }
}
