//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerAdv
    {
        public int banner_adv_id { get; set; }
        public string banner_adv_name { get; set; }
        public string banner_adv_photo { get; set; }
        public Nullable<int> banner_adv_position { get; set; }
        public Nullable<System.DateTime> banner_adv_fromdate { get; set; }
        public Nullable<System.DateTime> banner_adv_todate { get; set; }
    }
}
