//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public building()
        {
            this.offices = new HashSet<office>();
        }
    
        public int bulding_id { get; set; }
        public string bulding_name { get; set; }
        public string building_url { get; set; }
        public Nullable<int> city_id { get; set; }
        public string district { get; set; }
        public string provinces { get; set; }
        public string building_address { get; set; }
        public string building_picture { get; set; }
        public string building_phonenumber { get; set; }
        public string building_email { get; set; }
        public string building_fanpage { get; set; }
        public string building_latlong { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<office> offices { get; set; }
    }
}
