//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_rent
    {
        public long id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string message { get; set; }
        public Nullable<long> office_id { get; set; }
        public string office_name { get; set; }
        public Nullable<System.DateTime> contact_date { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
