//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu()
        {
            this.menus1 = new HashSet<menu>();
        }
    
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string menu_url { get; set; }
        public Nullable<int> menu_parent_id { get; set; }
        public Nullable<int> menu_position { get; set; }
        public Nullable<int> menu_position_index { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menus1 { get; set; }
        public virtual menu menu1 { get; set; }
    }
}
