//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class office_photos
    {
        public long photo_id { get; set; }
        public string photo_url { get; set; }
        public string photo_title { get; set; }
        public string photo_alt { get; set; }
        public Nullable<long> office_id { get; set; }
    
        public virtual office office { get; set; }
    }
}
