//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class officerentalEntities : DbContext
    {
        public officerentalEntities()
            : base("name=officerentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleCategory> ArticleCategories { get; set; }
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<building> buildings { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<office> offices { get; set; }
        public virtual DbSet<OfficeService> OfficeServices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BannerAdv> BannerAdvs { get; set; }
        public virtual DbSet<contact_rent> contact_rent { get; set; }
        public virtual DbSet<register_email> register_email { get; set; }
    }
}
