//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOfficeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public office()
        {
            this.OfficeServices = new HashSet<OfficeService>();
        }
    
        public long office_id { get; set; }
        public string office_name { get; set; }
        public Nullable<int> office_type { get; set; }
        public Nullable<int> office_new_type { get; set; }
        public string office_address { get; set; }
        public Nullable<int> office_price_public { get; set; }
        public string office_hotmail { get; set; }
        public string office_hotline { get; set; }
        public string office_fanpage { get; set; }
        public Nullable<int> office_acreage { get; set; }
        public Nullable<int> office_door { get; set; }
        public Nullable<int> office_table { get; set; }
        public string office_photo { get; set; }
        public string office_photo_slider { get; set; }
        public string office_other_descriptions { get; set; }
        public Nullable<int> office_views { get; set; }
        public Nullable<int> office_votes { get; set; }
        public string office_connection { get; set; }
        public Nullable<int> buiding_id { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public Nullable<bool> status { get; set; }
        public string office_unit { get; set; }
    
        public virtual building building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeService> OfficeServices { get; set; }
    }
}
