USE [database_TinhThanh]
GO
/****** Object:  Table [dbo].[cities]    Script Date: 11/7/2016 3:40:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cities](
	[id] [int] NOT NULL,
	[district] [nvarchar](255) NULL,
	[provinces] [nvarchar](255) NULL
) ON [PRIMARY]

GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (1, N'A Lưới', N'Thừa Thiên-Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (2, N'An Biên', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (3, N'An Dương', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (4, N'An Khê', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (5, N'An Lão', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (6, N'An Lão', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (7, N'An Minh', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (8, N'An Nhơn', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (9, N'An Phú', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (10, N'Anh Sơn', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (11, N'Ayun Pa', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (12, N'Ân Thi', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (13, N'Ba Bể', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (14, N'Ba Chẽ', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (15, N'Ba Đình', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (16, N'Ba Đồn', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (17, N'Ba Tơ', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (18, N'Ba Tri', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (19, N'Ba Vì', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (20, N'Bà Rịa', N'Bà Rịa-Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (21, N'Bá Thước', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (22, N'Bác Ái', N'Ninh Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (23, N'Bạc Liêu', N'Bạc Liêu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (24, N'Bạch Long Vĩ', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (25, N'Bạch Thông', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (26, N'Bảo Lạc', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (27, N'Bảo Lâm', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (28, N'Bảo Lâm', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (29, N'Bảo Lộc', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (30, N'Bảo Thắng', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (31, N'Bảo Yên', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (32, N'Bát Xát', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (33, N'Bàu Bàng', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (34, N'Bắc Bình', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (35, N'Bắc Giang', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (36, N'Bắc Hà', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (37, N'Bắc Kạn', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (38, N'Bắc Mê', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (39, N'Bắc Ninh', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (40, N'Bắc Quang', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (41, N'Bắc Sơn', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (42, N'Bắc Tân Uyên', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (43, N'Bắc Trà My', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (44, N'Bắc Từ Liêm', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (45, N'Bắc Yên', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (46, N'Bến Cát', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (47, N'Bến Cầu', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (48, N'Bến Lức', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (49, N'Bến Tre', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (50, N'Biên Hòa', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (51, N'Bỉm Sơn', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (52, N'Bình Chánh', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (53, N'Bình Đại', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (54, N'Bình Gia', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (55, N'Bình Giang', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (56, N'Bình Liêu', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (57, N'Bình Long', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (58, N'Bình Lục', N'Hà Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (59, N'Bình Minh', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (60, N'Bình Sơn', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (61, N'Bình Tân', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (62, N'Bình Tân', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (63, N'Bình Thạnh', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (64, N'Bình Thủy', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (65, N'Bình Xuyên', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (66, N'Bố Trạch', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (67, N'Bù Đăng', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (68, N'Bù Đốp', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (69, N'Bù Gia Mập', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (70, N'Buôn Đôn', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (71, N'Buôn Hồ', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (72, N'Buôn Ma Thuột', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (73, N'Cà Mau', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (74, N'Cai Lậy', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (75, N'Cai Lậy', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (76, N'Cái Bè', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (77, N'Cái Nước', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (78, N'Cái Răng', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (79, N'Cam Lâm', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (80, N'Cam Lộ', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (81, N'Cam Ranh', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (82, N'Can Lộc', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (83, N'Càng Long', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (84, N'Cao Bằng', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (85, N'Cao Lãnh', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (86, N'Cao Lãnh', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (87, N'Cao Lộc', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (88, N'Cao Phong', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (89, N'Cát Hải', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (90, N'Cát Tiên', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (91, N'Cẩm Giàng', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (92, N'Cẩm Khê', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (93, N'Cẩm Lệ', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (94, N'Cẩm Mỹ', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (95, N'Cẩm Phả', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (96, N'Cẩm Thủy', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (97, N'Cẩm Xuyên', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (98, N'Cần Đước', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (99, N'Cần Giờ', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (100, N'Cần Giuộc', N'Long An')
GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (101, N'Cầu Giấy', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (102, N'Cầu Kè', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (103, N'Cầu Ngang', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (104, N'Châu Đốc', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (105, N'Châu Đức', N'Bà Rịa-Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (106, N'Châu Phú', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (107, N'Châu Thành', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (108, N'Châu Thành', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (109, N'Châu Thành', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (110, N'Châu Thành', N'Hậu Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (111, N'Châu Thành', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (112, N'Châu Thành', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (113, N'Châu Thành', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (114, N'Châu Thành', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (115, N'Châu Thành', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (116, N'Châu Thành', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (117, N'Châu Thành A', N'Hậu Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (118, N'Chi Lăng', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (119, N'Chí Linh', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (120, N'Chiêm Hóa', N'Tuyên Quang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (121, N'Chợ Đồn', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (122, N'Chợ Gạo', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (123, N'Chợ Lách', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (124, N'Chợ Mới', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (125, N'Chợ Mới', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (126, N'Chơn Thành', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (127, N'Chư Păh', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (128, N'Chư Prông', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (129, N'Chư Pưh', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (130, N'Chư Sê', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (131, N'Chương Mỹ', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (132, N'Con Cuông', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (133, N'Cô Tô', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (134, N'Côn Đảo', N'Bà Rịa-Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (135, N'Cồn Cỏ', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (136, N'Cờ Đỏ', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (137, N'Cù Lao Dung', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (138, N'Củ Chi', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (139, N'Cư Kuin', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (140, N'Cư Jút', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (141, N'Cư M''gar', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (142, N'Cửa Lò', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (143, N'Dầu Tiếng', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (144, N'Di Linh', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (145, N'Dĩ An', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (146, N'Diên Khánh', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (147, N'Diễn Châu', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (148, N'Duy Tiên', N'Hà Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (149, N'Duy Xuyên', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (150, N'Duyên Hải', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (151, N'Dương Kinh', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (152, N'Dương Minh Châu', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (153, N'Đa Krông', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (154, N'Đà Bắc', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (155, N'Đà Lạt', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (156, N'Đạ Huoai', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (157, N'Đạ Tẻh', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (158, N'Đại Lộc', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (159, N'Đại Từ', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (160, N'Đăk Đoa', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (161, N'Đắk Pơ', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (162, N'Đan Phượng', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (163, N'Đắk Glei', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (164, N'Đăk Glong', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (165, N'Đắk Hà', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (166, N'Đăk Mil', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (167, N'Đăk R''Lấp', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (168, N'Đăk Song', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (169, N'Đăk Tô', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (170, N'Đầm Dơi', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (171, N'Đầm Hà', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (172, N'Đam Rông', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (173, N'Đất Đỏ', N'Bà Rịa-Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (174, N'Điện Bàn', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (175, N'Điện Biên', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (176, N'Điện Biên Đông', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (177, N'Điện Biên Phủ', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (178, N'Đình Lập', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (179, N'Định Hóa', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (180, N'Định Quán', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (181, N'Đoan Hùng', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (182, N'Đô Lương', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (183, N'Đồ Sơn', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (184, N'Đông Anh', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (185, N'Đông Giang', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (186, N'Đông Hà', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (187, N'Đông Hải', N'Bạc Liêu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (188, N'Đông Hòa', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (189, N'Đông Hưng', N'Thái Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (190, N'Đông Sơn', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (191, N'Đông Triều', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (192, N'Đồng Hới', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (193, N'Đồng Hỷ', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (194, N'Đồng Phú', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (195, N'Đồng Văn', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (196, N'Đồng Xoài', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (197, N'Đồng Xuân', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (198, N'Đống Đa', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (199, N'Đơn Dương', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (200, N'Đức Cơ', N'Gia Lai')
GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (201, N'Đức Hòa', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (202, N'Đức Huệ', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (203, N'Đức Linh', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (204, N'Đức Phổ', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (205, N'Đức Thọ', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (206, N'Đức Trọng', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (207, N'Ea H''leo', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (208, N'Ea Kar', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (209, N'Ea Súp', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (210, N'Gia Bình', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (211, N'Gia Lâm', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (212, N'Gia Lộc', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (213, N'Gia Nghĩa', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (214, N'Gia Viễn', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (215, N'Giá Rai', N'Bạc Liêu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (216, N'Giang Thành', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (217, N'Giao Thủy', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (218, N'Gio Linh', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (219, N'Giồng Riềng', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (220, N'Giồng Trôm', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (221, N'Gò Công', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (222, N'Gò Công Đông', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (223, N'Gò Công Tây', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (224, N'Gò Dầu', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (225, N'Gò Quao', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (226, N'Gò Vấp', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (227, N'Hà Đông', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (228, N'Hà Giang', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (229, N'Hà Quảng', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (230, N'Hà Tiên', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (231, N'Hà Tĩnh', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (232, N'Hà Trung', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (233, N'Hạ Hòa', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (234, N'Hạ Lang', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (235, N'Hạ Long', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (236, N'Hai Bà Trưng', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (237, N'Hải An', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (238, N'Hải Châu', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (239, N'Hải Dương', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (240, N'Hải Hà', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (241, N'Hải Hậu', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (242, N'Hải Lăng', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (243, N'Hàm Tân', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (244, N'Hàm Thuận Bắc', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (245, N'Hàm Thuận Nam', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (246, N'Hàm Yên', N'Tuyên Quang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (247, N'Hậu Lộc', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (248, N'Hiệp Đức', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (249, N'Hiệp Hòa', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (250, N'Hoa Lư', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (251, N'Hòa An', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (252, N'Hoà Bình', N'Bạc Liêu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (253, N'Hoà Bình', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (254, N'Hòa Thành', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (255, N'Hoà Vang', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (256, N'Hoài Ân', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (257, N'Hoài Đức', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (258, N'Hoài Nhơn', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (259, N'Hoàn Kiếm', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (260, N'Hoàng Mai', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (261, N'Hoàng Mai', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (262, N'Hoàng Sa', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (263, N'Hoàng Su Phì', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (264, N'Hoành Bồ', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (265, N'Hoằng Hóa', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (266, N'Hóc Môn', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (267, N'Hòn Đất', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (268, N'Hớn Quản', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (269, N'Hội An', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (270, N'Hồng Bàng', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (271, N'Hồng Dân', N'Bạc Liêu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (272, N'Hồng Lĩnh', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (273, N'Hồng Ngự', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (274, N'Hồng Ngự', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (275, N'Huế', N'Thừa Thiên - Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (276, N'Hưng Hà', N'Thái Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (277, N'Hưng Nguyên', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (278, N'Hưng Yên', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (279, N'Hương Khê', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (280, N'Hương Sơn', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (281, N'Hương Thủy', N'Thừa Thiên - Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (282, N'Hương Trà', N'Thừa Thiên - Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (283, N'Hướng Hóa', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (284, N'Hữu Lũng', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (285, N'Ia Grai', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (286, N'Ia Pa', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (287, N'KBang', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (288, N'Kế Sách', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (289, N'Khánh Sơn', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (290, N'Khánh Vĩnh', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (291, N'Khoái Châu', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (292, N'Kiên Hải', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (293, N'Kiên Lương', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (294, N'Kiến An', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (295, N'Kiến Thụy', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (296, N'Kiến Xương', N'Thái Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (297, N'Kiến Tường', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (298, N'Kim Bảng', N'Hà Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (299, N'Kim Bôi', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (300, N'Kim Động', N'Hưng Yên')
GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (301, N'Kim Sơn', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (302, N'Kim Thành', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (303, N'Kinh Môn', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (304, N'Kon Plông', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (305, N'Kon Rẫy', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (306, N'Kon Tum', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (307, N'Kông Chro', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (308, N'Krông Ana', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (309, N'Krông Bông', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (310, N'Krông Búk', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (311, N'Krông Năng', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (312, N'Krông Nô', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (313, N'Krông Pa', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (314, N'Krông Pắk', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (315, N'Kỳ Anh', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (316, N'Kỳ Sơn', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (317, N'Kỳ Sơn', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (318, N'La Gi', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (319, N'Lạc Dương', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (320, N'Lạc Sơn', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (321, N'Lạc Thủy', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (322, N'Lai Châu', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (323, N'Lai Vung', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (324, N'Lang Chánh', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (325, N'Lạng Giang', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (326, N'Lạng Sơn', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (327, N'Lào Cai', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (328, N'Lắk', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (329, N'Lâm Bình', N'Tuyên Quang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (330, N'Lâm Hà', N'Lâm Đồng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (331, N'Lâm Thao', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (332, N'Lấp Vò', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (333, N'Lập Thạch', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (334, N'Lê Chân', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (335, N'Lệ Thủy', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (336, N'Liên Chiểu', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (337, N'Long Biên', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (338, N'Long Điền', N'Bà Rịa-Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (339, N'Long Hồ', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (340, N'Long Khánh', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (341, N'Long Mỹ', N'Hậu Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (342, N'Long Phú', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (343, N'Long Thành', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (344, N'Long Xuyên', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (345, N'Lộc Bình', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (346, N'Lộc Hà', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (347, N'Lộc Ninh', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (348, N'Lục Nam', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (349, N'Lục Ngạn', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (350, N'Lục Yên', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (351, N'Lương Sơn', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (352, N'Lương Tài', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (353, N'Lý Nhân', N'Hà Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (354, N'Lý Sơn', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (355, N'Mai Châu', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (356, N'Mai Sơn', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (357, N'Mang Thít', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (358, N'Mang Yang', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (359, N'M''Đrăk', N'Đăk Lăk')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (360, N'Mèo Vạc', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (361, N'Mê Linh', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (362, N'Minh Hóa', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (363, N'Minh Long', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (364, N'Mỏ Cày Bắc', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (365, N'Mỏ Cày Nam', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (366, N'Móng Cái', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (367, N'Mộ Đức', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (368, N'Mộc Châu', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (369, N'Mộc Hóa', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (370, N'Mù Căng Chải', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (371, N'Mường Ảng', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (372, N'Mường Chà', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (373, N'Mường Khương', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (374, N'Mường La', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (375, N'Mường Lát', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (376, N'Mường Lay', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (377, N'Mường Nhé', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (378, N'Mường Tè', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (379, N'Mỹ Đức', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (380, N'Mỹ Hào', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (381, N'Mỹ Lộc', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (382, N'Mỹ Tho', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (383, N'Mỹ Tú', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (384, N'Mỹ Xuyên', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (385, N'Na Hang', N'Tuyên Quang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (386, N'Na Rì', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (387, N'Nam Đàn', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (388, N'Nam Định', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (389, N'Nam Đông', N'Thừa Thiên - Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (390, N'Nam Giang', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (391, N'Nam Sách', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (392, N'Nam Trà My', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (393, N'Nam Trực', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (394, N'Nam Từ Liêm', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (395, N'Năm Căn', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (396, N'Nậm Pồ', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (397, N'Nậm Nhùn', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (398, N'Nga Sơn', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (399, N'Ngã Bảy', N'Hậu Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (400, N'Ngã Năm', N'Sóc Trăng')
GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (401, N'Ngân Sơn', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (402, N'Nghi Lộc', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (403, N'Nghi Xuân', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (404, N'Nghĩa Đàn', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (405, N'Nghĩa Hành', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (406, N'Nghĩa Hưng', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (407, N'Nghĩa Lộ', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (408, N'Ngọc Hiển', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (409, N'Ngọc Hồi', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (410, N'Ngọc Lặc', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (411, N'Ngô Quyền', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (412, N'Ngũ Hành Sơn', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (413, N'Nguyên Bình', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (414, N'Nha Trang', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (415, N'Nhà Bè', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (416, N'Nho Quan', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (417, N'Nhơn Trạch', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (418, N'Như Thanh', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (419, N'Như Xuân', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (420, N'Ninh Bình', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (421, N'Ninh Giang', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (422, N'Ninh Hải', N'Ninh Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (423, N'Ninh Hòa', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (424, N'Ninh Kiều', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (425, N'Ninh Phước', N'Ninh Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (426, N'Ninh Sơn', N'Ninh Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (427, N'Nông Cống', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (428, N'Nông Sơn', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (429, N'Núi Thành', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (430, N'Ô Môn', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (431, N'Pác Nặm', N'Bắc Kạn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (432, N'Phan Rang-Tháp Chàm', N'Ninh Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (433, N'Phan Thiết', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (434, N'Phong Điền', N'Thừa Thiên-Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (435, N'Phong Điền', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (436, N'Phong Thổ', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (437, N'Phổ Yên', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (438, N'Phú Bình', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (439, N'Phú Giáo', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (440, N'Phú Hòa', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (441, N'Phú Lộc', N'Thừa Thiên-Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (442, N'Phú Lương', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (443, N'Phú Nhuận', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (444, N'Phú Ninh', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (445, N'Phú Quý', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (446, N'Phú Quốc', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (447, N'Phú Tân', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (448, N'Phú Tân', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (449, N'Phú Thiện', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (450, N'Phú Thọ', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (451, N'Phú Vang', N'Thừa Thiên-Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (452, N'Phú Xuyên', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (453, N'Phù Cát', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (454, N'Phù Cừ', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (455, N'Phù Mỹ', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (456, N'Phù Ninh', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (457, N'Phù Yên', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (458, N'Phủ Lý', N'Hà Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (459, N'Phúc Thọ', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (460, N'Phúc Yên', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (461, N'Phục Hòa', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (462, N'Phụng Hiệp', N'Hậu Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (463, N'Phước Long', N'Bình Phước')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (464, N'Phước Long', N'Bạc Liêu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (465, N'Phước Sơn', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (466, N'Pleiku', N'Gia Lai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (467, N'Quan Hóa', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (468, N'Quan Sơn', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (469, N'Quản Bạ', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (470, N'Quang Bình', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (471, N'Quảng Điền', N'Thừa Thiên-Huế')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (472, N'Quảng Ngãi', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (473, N'Quảng Ninh', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (474, N'Quảng Trạch', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (475, N'Quảng Trị', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (476, N'Quảng Yên', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (477, N'Quảng Uyên', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (478, N'Quảng Xương', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (479, N'Quận 1', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (480, N'Quận 2', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (481, N'Quận 3', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (482, N'Quận 4', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (483, N'Quận 5', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (484, N'Quận 6', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (485, N'Quận 7', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (486, N'Quận 8', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (487, N'Quận 9', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (488, N'Quận 10', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (489, N'Quận 11', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (490, N'Quận 12', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (491, N'Quế Phong', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (492, N'Quế Sơn', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (493, N'Quế Võ', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (494, N'Qui Nhơn', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (495, N'Quốc Oai', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (496, N'Quỳ Châu', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (497, N'Quỳ Hợp', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (498, N'Quỳnh Lưu', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (499, N'Quỳnh Nhai', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (500, N'Quỳnh Phụ', N'Thái Bình')
GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (501, N'Rạch Giá', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (502, N'Sa Đéc', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (503, N'Sa Pa', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (504, N'Sa Thầy', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (505, N'Sầm Sơn', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (506, N'Si Ma Cai', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (507, N'Sìn Hồ', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (508, N'Sóc Sơn', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (509, N'Sóc Trăng', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (510, N'Sông Cầu', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (511, N'Sông Công', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (512, N'Sông Hinh', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (513, N'Sông Lô', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (514, N'Sông Mã', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (515, N'Sốp Cộp', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (516, N'Sơn Động', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (517, N'Sơn Dương', N'Tuyên Quang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (518, N'Sơn Hà', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (519, N'Sơn Hòa', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (520, N'Sơn La', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (521, N'Sơn Tây', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (522, N'Sơn Tây', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (523, N'Sơn Tịnh', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (524, N'Sơn Trà', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (525, N'Tam Bình', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (526, N'Tam Dương', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (527, N'Tam Đảo', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (528, N'Tam Điệp', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (529, N'Tam Đường', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (530, N'Tam Kỳ', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (531, N'Tam Nông', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (532, N'Tam Nông', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (533, N'Tánh Linh', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (534, N'Tân An', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (535, N'Tân Biên', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (536, N'Tân Bình', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (537, N'Tân Châu', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (538, N'Tân Châu', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (539, N'Tân Hiệp', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (540, N'Tân Hồng', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (541, N'Tân Hưng', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (542, N'Tân Kỳ', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (543, N'Tân Lạc', N'Hoà Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (544, N'Tân Phú', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (545, N'Tân Phú', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (546, N'Tân Phú Đông', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (547, N'Tân Phước', N'Tiền Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (548, N'Tân Sơn', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (549, N'Tân Thành', N'Bà Rịa - Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (550, N'Tân Thạnh', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (551, N'Tân Trụ', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (552, N'Tân Uyên', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (553, N'Tân Uyên', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (554, N'Tân Yên', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (555, N'Tây Giang', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (556, N'Tây Hòa', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (557, N'Tây Hồ', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (558, N'Tây Ninh', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (559, N'Tây Sơn', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (560, N'Tây Trà', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (561, N'Thạch An', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (562, N'Thạch Hà', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (563, N'Thạch Thành', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (564, N'Thạch Thất', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (565, N'Thái Bình', N'Thái Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (566, N'Thái Hòa', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (567, N'Thái Nguyên', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (568, N'Thái Thụy', N'Thái Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (569, N'Than Uyên', N'Lai Châu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (570, N'Thanh Ba', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (571, N'Thanh Bình', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (572, N'Thanh Chương', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (573, N'Thanh Hà', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (574, N'Thanh Hóa', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (575, N'Thanh Khê', N'Đà Nẵng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (576, N'Thanh Liêm', N'Hà Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (577, N'Thanh Miện', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (578, N'Thanh Oai', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (579, N'Thanh Sơn', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (580, N'Thanh Thủy', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (581, N'Thanh Trì', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (582, N'Thanh Xuân', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (583, N'Thạnh Hóa', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (584, N'Thạnh Phú', N'Bến Tre')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (585, N'Thạnh Trị', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (586, N'Tháp Mười', N'Đồng Tháp')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (587, N'Thăng Bình', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (588, N'Thiệu Hóa', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (589, N'Thọ Xuân', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (590, N'Thoại Sơn', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (591, N'Thông Nông', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (592, N'Thống Nhất', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (593, N'Thốt Nốt', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (594, N'Thới Bình', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (595, N'Thới Lai', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (596, N'Thủ Dầu Một', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (597, N'Thủ Đức', N'TP Hồ Chí Minh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (598, N'Thủ Thừa', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (599, N'Thuận An', N'Bình Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (600, N'Thuận Bắc', N'Ninh Thuận')
GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (601, N'Thuận Châu', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (602, N'Thuận Nam', N'Ninh Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (603, N'Thuận Thành', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (604, N'Thuỷ Nguyên', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (605, N'Thường Tín', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (606, N'Thường Xuân', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (607, N'Tiên Du', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (608, N'Tiền Hải', N'Thái Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (609, N'Tiên Lãng', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (610, N'Tiên Lữ', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (611, N'Tiên Phước', N'Quảng Nam')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (612, N'Tiên Yên', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (613, N'Tiểu Cần', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (614, N'Tĩnh Gia', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (615, N'Tịnh Biên', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (616, N'Trà Bồng', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (617, N'Trà Cú', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (618, N'Trà Lĩnh', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (619, N'Trà Ôn', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (620, N'Trà Vinh', N'Trà Vinh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (621, N'Trạm Tấu', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (622, N'Tràng Định', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (623, N'Trảng Bàng', N'Tây Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (624, N'Trảng Bom', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (625, N'Trấn Yên', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (626, N'Trần Đề', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (627, N'Trần Văn Thời', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (628, N'Tri Tôn', N'An Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (629, N'Triệu Phong', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (630, N'Triệu Sơn', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (631, N'Trùng Khánh', N'Cao Bằng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (632, N'Trực Ninh', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (633, N'Trường Sa', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (634, N'Tủa Chùa', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (635, N'Tuần Giáo', N'Điện Biên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (636, N'Tu Mơ Rông', N'Kon Tum')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (637, N'Tuy An', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (638, N'Tuy Đức', N'Đăk Nông')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (639, N'Tuy Hòa', N'Phú Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (640, N'Tuy Phong', N'Bình Thuận')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (641, N'Tuy Phước', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (642, N'Tuyên Hóa', N'Quảng Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (643, N'Tuyên Quang', N'Tuyên Quang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (644, N'Tư Nghĩa', N'Quảng Ngãi')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (645, N'Tứ Kỳ', N'Hải Dương')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (646, N'Từ Sơn', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (647, N'Tương Dương', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (648, N'U Minh', N'Cà Mau')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (649, N'U Minh Thượng', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (650, N'Uông Bí', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (651, N'Ứng Hòa', N'Hà Nội')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (652, N'Vạn Ninh', N'Khánh Hòa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (653, N'Văn Bàn', N'Lào Cai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (654, N'Văn Chấn', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (655, N'Văn Giang', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (656, N'Vãn Lãng', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (657, N'Văn Lâm', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (658, N'Văn Quan', N'Lạng Sơn')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (659, N'Văn Yên', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (660, N'Vân Canh', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (661, N'Vân Đồn', N'Quảng Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (662, N'Vân Hồ', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (663, N'Vị Thanh', N'Hậu Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (664, N'Vị Thủy', N'Hậu Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (665, N'Vị Xuyên', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (666, N'Việt Trì', N'Phú Thọ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (667, N'Việt Yên', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (668, N'Vinh', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (669, N'Vĩnh Bảo', N'Hải Phòng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (670, N'Vĩnh Châu', N'Sóc Trăng')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (671, N'Vĩnh Cửu', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (672, N'Vĩnh Hưng', N'Long An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (673, N'Vĩnh Linh', N'Quảng Trị')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (674, N'Vĩnh Long', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (675, N'Vĩnh Lộc', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (676, N'Vĩnh Lợi', N'Bạc Liêu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (677, N'Vĩnh Thạnh', N'Bình Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (678, N'Vĩnh Thạnh', N'Cần Thơ')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (679, N'Vĩnh Thuận', N'Kiên Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (680, N'Vĩnh Tường', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (681, N'Vĩnh Yên', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (682, N'Võ Nhai', N'Thái Nguyên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (683, N'Vũ Quang', N'Hà Tĩnh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (684, N'Vũ Thư', N'Thái Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (685, N'Vụ Bản', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (686, N'Vũng Liêm', N'Vĩnh Long')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (687, N'Vũng Tàu', N'Bà Rịa - Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (688, N'Xín Mần', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (689, N'Xuân Lộc', N'Đồng Nai')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (690, N'Xuân Trường', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (691, N'Xuyên Mộc', N'Bà Rịa - Vũng Tàu')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (692, N'Ý Yên', N'Nam Định')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (693, N'Yên Bái', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (694, N'Yên Bình', N'Yên Bái')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (695, N'Yên Châu', N'Sơn La')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (696, N'Yên Dũng', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (697, N'Yên Định', N'Thanh Hóa')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (698, N'Yên Khánh', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (699, N'Yên Lạc', N'Vĩnh Phúc')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (700, N'Yên Lập', N'Phú Thọ')
GO
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (701, N'Yên Minh', N'Hà Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (702, N'Yên Mô', N'Ninh Bình')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (703, N'Yên Mỹ', N'Hưng Yên')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (704, N'Yên Phong', N'Bắc Ninh')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (705, N'Yên Sơn', N'Tuyên Quang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (706, N'Yên Thành', N'Nghệ An')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (707, N'Yên Thế', N'Bắc Giang')
INSERT [dbo].[cities] ([id], [district], [provinces]) VALUES (708, N'Yên Thủy', N'Hoà Bình')
